name: Check Emacs Lisp
on:
  pull_request:
    paths-ignore:
      - 'README.*'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.*'
  workflow_dispatch:
jobs:
  compile-and-test:
    uses: emacs-twist/elisp-workflows/.github/workflows/compile-and-test.yml@master
    with:
      melpa: github:emacs-twist/melpa/nix3-all
      systems: github:nix-systems/x86_64-linux
