name: Lint and test

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.org'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix run .#nomake -- nix3
    - run: nix run .#nomake -- magit-nix3
