name: Lint and test

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.org'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: cachix/install-nix-action@v18
  #     with:
  #       extra_nix_config: |
  #         access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
  #   - run: nix run .#nomake -- nix3

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix run .#nomake -- nix3 byte-compile-and-load
    - run: nix run .#nomake -- magit-nix3 byte-compile-and-load
